server:
    port: 8082
spring:
    boot:
        admin:
            client:
                url: http://localhost:8083
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin
    application:
        name: review-client
management:
    endpoints:
        web:
            exposure:
                include: "*"
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/
feign:
    hystrix:
        enabled: true
mybatis-plus:
    global-config:
        db-config:
            # 逻辑删除字段(since 3.3.0,配置后可以忽略不配置步骤2)
            logic-delete-field: delete
            logic-delete-value: 1
            logic-not-delete-value: 0
    # 通用枚举类包扫描
    type-enums-package: org.liangxiong.review.client.enums
    mapper-locations: classpath*:/mapper/**/*.xml
logging:
    level:
        org.liangxiong.demo.mapper: DEBUG