server:
    port: 8888
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin
        application:
            name: review-admin