fdfs:
    so-timeout: 1501
    connect-timeout: 601
    #缩略图生成参数
    thumb-image:
        width: 150
        height: 150
    #TrackerList参数,支持多个
    tracker-list:
        - 192.168.199.70:22122
    #连接池配置
    pool:
        #从池中借出的对象的最大数目（配置为-1表示不限制）
        max-total: 100
        #获取连接时的最大等待毫秒数(默认配置为5秒)
        max-wait-millis: 5000
        #每个key最大连接数
        max-total-per-key: 50
        #每个key对应的连接池最大空闲连接数
        max-idle-per-key: 10
        #每个key对应的连接池最小空闲连接数
        max_idle_per_key: 5
spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 60MB
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin
    application:
        name: review-server
elasticsearch:
    cluster-name: liangxiong
    cluster-nodes: 192.168.199.2:9200,192.168.199.3:9200,192.168.199.4:9200
server:
    port: 8083
management:
    endpoints:
        web:
            exposure:
                include: "*"
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/
